### ISSUE TITLE
Improve Project Structure and Documentation

### ISSUE THREAD

**Issue by keys-i** [AnMaster15/daa#2]
The current project structure and documentation need significant improvements to enhance readability, maintainability, and ease of use. Below are the suggested changes to address these issues:

1. **Separate Code into Individual Files:**
   - Currently, all the algorithms and problem solutions are contained within a single file, making it difficult to navigate and maintain. Each algorithm or problem should be separated into its own `.cpp` file, with a clear and descriptive filename.
   - **Example:**
     - `huffman_coding.cpp`
     - `job_scheduling.cpp`
     - `fractional_knapsack.cpp`
     - `n_meetings.cpp`
     - `hamiltonian_cycle.cpp`
     - `majority_element.cpp`
     - `tsp.cpp`

2. **Add a README.md File:**
   - A `README.md` file is needed to provide an overview of the project, including descriptions of each algorithm/problem, instructions for compilation and execution, and any other relevant information.
   - The README should include the following sections:
     - **Project Title**
     - **Table of Contents**
     - **Description of Each Algorithm**
     - **Getting Started** (including prerequisites, compilation, and execution)
     - **Contributing Guidelines**
     - **License Information**

3. **Create a .gitignore File:**
   - A `.gitignore` file should be added to exclude unnecessary files from being tracked by Git. This includes compiled binaries, build directories, system-specific files, IDE-specific files, and more.
   - The `.gitignore` should include entries for:
     - **Binary files and executables** (e.g., `.exe`, `.out`, `.o`)
     - **Build system directories** (e.g., `/CMakeFiles`, `/Makefile`)
     - **System-specific files** (e.g., `.DS_Store`, `Thumbs.db`)
     - **IDE-specific files** (e.g., `.idea/`, `.vscode/`)

4. **Refactor Code for Consistency and Readability:**
   - Ensure that the code is consistent in terms of formatting, naming conventions, and commenting. This includes:
     - Proper indentation and spacing.
     - Consistent use of variable and function names.
     - Adequate comments explaining the purpose and logic of the code.

5. **Improve Documentation in Code:**
   - Each file should include a brief description at the top, explaining the problem being solved and the approach taken.
   - Comments should be added to critical sections of the code to improve understanding and maintainability.

**Impact:**
- These changes will significantly improve the project's structure, making it easier for contributors to navigate, understand, and extend. Additionally, proper documentation will help new users quickly get up to speed and contribute effectively.

**Steps to Implement:**
1. Create individual `.cpp` files for each algorithm/problem.
2. Write and add the `README.md` file with the necessary sections.
3. Add a `.gitignore` file to the root of the repository.
4. Refactor the existing code to improve consistency, readability, and documentation.
5. Review and test the changes before merging into the main branch.

**Comment by keys-i** [comment]
I have tried to fix by doing changes #1

**Comment by AnMaster15** [comment]
I have rewed your changes and  I think will look good to the repo.
